[profile.release]
panic = 'abort'
opt-level = 'z'
lto = 'thin'

# Speed up compiling the test harnesses themselves.
[profile.test]
opt-level = 0
debug = 0

[workspace]
resolver = "2"

members = [
  "rockc",
  "rock",
  "lib",
  "rockup",
  "rock-shared",
  "rock-lsp",
]

[workspace.package]
repository = "https://github.com/Rock-lang-org/Rock"
homepage = "https://rock-lang-org.github.io/Rock/"

[workspace.dependencies]
clap = { version = "4.5.3", features = ["derive"] }
ariadne = { version = "0.4.1", features = ["auto-color"] }
paste = "1.0.15"
inkwell = { version = "0.5", features = ["llvm18-0-force-static"] }
toml = "0.8"

# default-members = ["rock"]
