[crate]
name = "test_app"
version = "0.1.0"

[lib]
path = "src/main.rk"

[dependencies]
core_lib = { path = "crates/core_lib" }
data_lib = { path = "crates/data_lib" }
net_lib = { path = "crates/net_lib" }
