[package]
name = "rock-shared"
version = "0.5.2"
edition = "2021"
repository.workspace = true
homepage.workspace = true

[features]
default = ["manifest", "sysroot"]
manifest = ["dep:toml"]
sysroot = []
fs = []
process = []
serde = ["dep:serde"]

[dependencies]
toml = { workspace = true, optional = true }
serde = { version = "1.0", features = ["derive"], optional = true }
