//! Compiler intrinsic compilation.
//!
//! Handles lowering of typed intrinsics (I64Add, F32Mul, BoolAnd, etc.)
//! directly to LLVM instructions. These are generated by the resolver
//! for operator overloading on primitive types.

use inkwell::types::BasicType;
use inkwell::values::BasicValueEnum;
use inkwell::{AtomicOrdering, AtomicRMWBinOp, FloatPredicate, IntPredicate};

use crate::ids::TypeId;
use crate::mir::MirIntrinsicId;
use crate::type_context::Ty;
use crate::types::Type;

use super::{CodeGen, CodegenError};

impl<'ctx> CodeGen<'ctx> {
    pub(crate) fn compile_intrinsic_values(
        &mut self,
        intrinsic: MirIntrinsicId,
        compiled_args: &[BasicValueEnum<'ctx>],
        _ret_ty: &Type,
    ) -> Result<Option<BasicValueEnum<'ctx>>, CodegenError> {
        match intrinsic {
            MirIntrinsicId::I8Add
            | MirIntrinsicId::I16Add
            | MirIntrinsicId::I32Add
            | MirIntrinsicId::I64Add => {
                self.compile_int_intrinsic(compiled_args, "add", |this, lhs, rhs| {
                    this.builder.build_int_add(lhs, rhs, "add")
                })
            }
            MirIntrinsicId::U8Add
            | MirIntrinsicId::U16Add
            | MirIntrinsicId::U32Add
            | MirIntrinsicId::U64Add => {
                self.compile_uint_intrinsic(compiled_args, "add", |this, lhs, rhs| {
                    this.builder.build_int_add(lhs, rhs, "add")
                })
            }
            MirIntrinsicId::I8Sub
            | MirIntrinsicId::I16Sub
            | MirIntrinsicId::I32Sub
            | MirIntrinsicId::I64Sub => {
                self.compile_int_intrinsic(compiled_args, "sub", |this, lhs, rhs| {
                    this.builder.build_int_sub(lhs, rhs, "sub")
                })
            }
            MirIntrinsicId::U8Sub
            | MirIntrinsicId::U16Sub
            | MirIntrinsicId::U32Sub
            | MirIntrinsicId::U64Sub => {
                self.compile_uint_intrinsic(compiled_args, "sub", |this, lhs, rhs| {
                    this.builder.build_int_sub(lhs, rhs, "sub")
                })
            }
            MirIntrinsicId::I8Mul
            | MirIntrinsicId::I16Mul
            | MirIntrinsicId::I32Mul
            | MirIntrinsicId::I64Mul => {
                self.compile_int_intrinsic(compiled_args, "mul", |this, lhs, rhs| {
                    this.builder.build_int_mul(lhs, rhs, "mul")
                })
            }
            MirIntrinsicId::U8Mul
            | MirIntrinsicId::U16Mul
            | MirIntrinsicId::U32Mul
            | MirIntrinsicId::U64Mul => {
                self.compile_uint_intrinsic(compiled_args, "mul", |this, lhs, rhs| {
                    this.builder.build_int_mul(lhs, rhs, "mul")
                })
            }
            MirIntrinsicId::I8Div
            | MirIntrinsicId::I16Div
            | MirIntrinsicId::I32Div
            | MirIntrinsicId::I64Div => {
                self.compile_int_intrinsic(compiled_args, "sdiv", |this, lhs, rhs| {
                    this.builder.build_int_signed_div(lhs, rhs, "sdiv")
                })
            }
            MirIntrinsicId::U8Div
            | MirIntrinsicId::U16Div
            | MirIntrinsicId::U32Div
            | MirIntrinsicId::U64Div => {
                self.compile_uint_intrinsic(compiled_args, "udiv", |this, lhs, rhs| {
                    this.builder.build_int_unsigned_div(lhs, rhs, "udiv")
                })
            }
            MirIntrinsicId::I8Mod
            | MirIntrinsicId::I16Mod
            | MirIntrinsicId::I32Mod
            | MirIntrinsicId::I64Mod => {
                self.compile_int_intrinsic(compiled_args, "srem", |this, lhs, rhs| {
                    this.builder.build_int_signed_rem(lhs, rhs, "srem")
                })
            }
            MirIntrinsicId::U8Mod
            | MirIntrinsicId::U16Mod
            | MirIntrinsicId::U32Mod
            | MirIntrinsicId::U64Mod => {
                self.compile_uint_intrinsic(compiled_args, "urem", |this, lhs, rhs| {
                    this.builder.build_int_unsigned_rem(lhs, rhs, "urem")
                })
            }
            MirIntrinsicId::I8Neg
            | MirIntrinsicId::I16Neg
            | MirIntrinsicId::I32Neg
            | MirIntrinsicId::I64Neg => {
                let val = compiled_args[0].into_int_value();
                Ok(Some(
                    self.builder
                        .build_int_neg(val, "neg")
                        .map_err(|e| CodegenError::from(format!("Failed to build neg: {}", e)))?
                        .into(),
                ))
            }
            MirIntrinsicId::I8Not
            | MirIntrinsicId::I16Not
            | MirIntrinsicId::I32Not
            | MirIntrinsicId::I64Not
            | MirIntrinsicId::U8Not
            | MirIntrinsicId::U16Not
            | MirIntrinsicId::U32Not
            | MirIntrinsicId::U64Not
            | MirIntrinsicId::BoolNot => {
                let val = compiled_args[0].into_int_value();
                Ok(Some(
                    self.builder
                        .build_not(val, "not")
                        .map_err(|e| CodegenError::from(format!("Failed to build not: {}", e)))?
                        .into(),
                ))
            }
            MirIntrinsicId::I8And
            | MirIntrinsicId::I16And
            | MirIntrinsicId::I32And
            | MirIntrinsicId::I64And
            | MirIntrinsicId::BoolAnd => {
                self.compile_int_intrinsic(compiled_args, "and", |this, lhs, rhs| {
                    this.builder.build_and(lhs, rhs, "and")
                })
            }
            MirIntrinsicId::U8And
            | MirIntrinsicId::U16And
            | MirIntrinsicId::U32And
            | MirIntrinsicId::U64And => {
                self.compile_uint_intrinsic(compiled_args, "and", |this, lhs, rhs| {
                    this.builder.build_and(lhs, rhs, "and")
                })
            }
            MirIntrinsicId::I8Or
            | MirIntrinsicId::I16Or
            | MirIntrinsicId::I32Or
            | MirIntrinsicId::I64Or
            | MirIntrinsicId::BoolOr => {
                self.compile_int_intrinsic(compiled_args, "or", |this, lhs, rhs| {
                    this.builder.build_or(lhs, rhs, "or")
                })
            }
            MirIntrinsicId::U8Or
            | MirIntrinsicId::U16Or
            | MirIntrinsicId::U32Or
            | MirIntrinsicId::U64Or => {
                self.compile_uint_intrinsic(compiled_args, "or", |this, lhs, rhs| {
                    this.builder.build_or(lhs, rhs, "or")
                })
            }
            MirIntrinsicId::I8Xor
            | MirIntrinsicId::I16Xor
            | MirIntrinsicId::I32Xor
            | MirIntrinsicId::I64Xor
            | MirIntrinsicId::BoolXor => {
                self.compile_int_intrinsic(compiled_args, "xor", |this, lhs, rhs| {
                    this.builder.build_xor(lhs, rhs, "xor")
                })
            }
            MirIntrinsicId::U8Xor
            | MirIntrinsicId::U16Xor
            | MirIntrinsicId::U32Xor
            | MirIntrinsicId::U64Xor => {
                self.compile_uint_intrinsic(compiled_args, "xor", |this, lhs, rhs| {
                    this.builder.build_xor(lhs, rhs, "xor")
                })
            }
            MirIntrinsicId::I8Shl
            | MirIntrinsicId::I16Shl
            | MirIntrinsicId::I32Shl
            | MirIntrinsicId::I64Shl => {
                self.compile_int_intrinsic(compiled_args, "shl", |this, lhs, rhs| {
                    this.builder.build_left_shift(lhs, rhs, "shl")
                })
            }
            MirIntrinsicId::U8Shl
            | MirIntrinsicId::U16Shl
            | MirIntrinsicId::U32Shl
            | MirIntrinsicId::U64Shl => {
                self.compile_uint_intrinsic(compiled_args, "shl", |this, lhs, rhs| {
                    this.builder.build_left_shift(lhs, rhs, "shl")
                })
            }
            MirIntrinsicId::I8Shr
            | MirIntrinsicId::I16Shr
            | MirIntrinsicId::I32Shr
            | MirIntrinsicId::I64Shr => {
                self.compile_int_intrinsic(compiled_args, "shr", |this, lhs, rhs| {
                    this.builder.build_right_shift(lhs, rhs, true, "shr")
                })
            }
            MirIntrinsicId::U8Shr
            | MirIntrinsicId::U16Shr
            | MirIntrinsicId::U32Shr
            | MirIntrinsicId::U64Shr => {
                self.compile_uint_intrinsic(compiled_args, "shr", |this, lhs, rhs| {
                    this.builder.build_right_shift(lhs, rhs, false, "shr")
                })
            }
            MirIntrinsicId::I8Lt
            | MirIntrinsicId::I16Lt
            | MirIntrinsicId::I32Lt
            | MirIntrinsicId::I64Lt => {
                self.compile_int_compare_intrinsic(compiled_args, IntPredicate::SLT)
            }
            MirIntrinsicId::I8Le
            | MirIntrinsicId::I16Le
            | MirIntrinsicId::I32Le
            | MirIntrinsicId::I64Le => {
                self.compile_int_compare_intrinsic(compiled_args, IntPredicate::SLE)
            }
            MirIntrinsicId::I8Gt
            | MirIntrinsicId::I16Gt
            | MirIntrinsicId::I32Gt
            | MirIntrinsicId::I64Gt => {
                self.compile_int_compare_intrinsic(compiled_args, IntPredicate::SGT)
            }
            MirIntrinsicId::I8Ge
            | MirIntrinsicId::I16Ge
            | MirIntrinsicId::I32Ge
            | MirIntrinsicId::I64Ge => {
                self.compile_int_compare_intrinsic(compiled_args, IntPredicate::SGE)
            }
            MirIntrinsicId::U8Lt
            | MirIntrinsicId::U16Lt
            | MirIntrinsicId::U32Lt
            | MirIntrinsicId::U64Lt => {
                self.compile_uint_compare_intrinsic(compiled_args, IntPredicate::ULT)
            }
            MirIntrinsicId::U8Le
            | MirIntrinsicId::U16Le
            | MirIntrinsicId::U32Le
            | MirIntrinsicId::U64Le => {
                self.compile_uint_compare_intrinsic(compiled_args, IntPredicate::ULE)
            }
            MirIntrinsicId::U8Gt
            | MirIntrinsicId::U16Gt
            | MirIntrinsicId::U32Gt
            | MirIntrinsicId::U64Gt => {
                self.compile_uint_compare_intrinsic(compiled_args, IntPredicate::UGT)
            }
            MirIntrinsicId::U8Ge
            | MirIntrinsicId::U16Ge
            | MirIntrinsicId::U32Ge
            | MirIntrinsicId::U64Ge => {
                self.compile_uint_compare_intrinsic(compiled_args, IntPredicate::UGE)
            }
            MirIntrinsicId::I8Eq
            | MirIntrinsicId::I16Eq
            | MirIntrinsicId::I32Eq
            | MirIntrinsicId::I64Eq
            | MirIntrinsicId::BoolEq => {
                self.compile_int_compare_intrinsic(compiled_args, IntPredicate::EQ)
            }
            MirIntrinsicId::U8Eq
            | MirIntrinsicId::U16Eq
            | MirIntrinsicId::U32Eq
            | MirIntrinsicId::U64Eq => {
                self.compile_uint_compare_intrinsic(compiled_args, IntPredicate::EQ)
            }
            MirIntrinsicId::I8Ne
            | MirIntrinsicId::I16Ne
            | MirIntrinsicId::I32Ne
            | MirIntrinsicId::I64Ne
            | MirIntrinsicId::BoolNe => {
                self.compile_int_compare_intrinsic(compiled_args, IntPredicate::NE)
            }
            MirIntrinsicId::U8Ne
            | MirIntrinsicId::U16Ne
            | MirIntrinsicId::U32Ne
            | MirIntrinsicId::U64Ne => {
                self.compile_uint_compare_intrinsic(compiled_args, IntPredicate::NE)
            }
            MirIntrinsicId::F32Add | MirIntrinsicId::F64Add => {
                self.compile_float_intrinsic(compiled_args, "fadd", |this, lhs, rhs| {
                    this.builder.build_float_add(lhs, rhs, "fadd")
                })
            }
            MirIntrinsicId::F32Sub | MirIntrinsicId::F64Sub => {
                self.compile_float_intrinsic(compiled_args, "fsub", |this, lhs, rhs| {
                    this.builder.build_float_sub(lhs, rhs, "fsub")
                })
            }
            MirIntrinsicId::F32Mul | MirIntrinsicId::F64Mul => {
                self.compile_float_intrinsic(compiled_args, "fmul", |this, lhs, rhs| {
                    this.builder.build_float_mul(lhs, rhs, "fmul")
                })
            }
            MirIntrinsicId::F32Div | MirIntrinsicId::F64Div => {
                self.compile_float_intrinsic(compiled_args, "fdiv", |this, lhs, rhs| {
                    this.builder.build_float_div(lhs, rhs, "fdiv")
                })
            }
            MirIntrinsicId::F32Mod | MirIntrinsicId::F64Mod => {
                self.compile_float_intrinsic(compiled_args, "frem", |this, lhs, rhs| {
                    this.builder.build_float_rem(lhs, rhs, "frem")
                })
            }
            MirIntrinsicId::F32Neg | MirIntrinsicId::F64Neg => {
                let val = compiled_args[0].into_float_value();
                Ok(Some(
                    self.builder
                        .build_float_neg(val, "fneg")
                        .map_err(|e| CodegenError::from(format!("Failed to build fneg: {}", e)))?
                        .into(),
                ))
            }
            MirIntrinsicId::F32Lt | MirIntrinsicId::F64Lt => {
                self.compile_float_compare_intrinsic(compiled_args, FloatPredicate::OLT)
            }
            MirIntrinsicId::F32Le | MirIntrinsicId::F64Le => {
                self.compile_float_compare_intrinsic(compiled_args, FloatPredicate::OLE)
            }
            MirIntrinsicId::F32Gt | MirIntrinsicId::F64Gt => {
                self.compile_float_compare_intrinsic(compiled_args, FloatPredicate::OGT)
            }
            MirIntrinsicId::F32Ge | MirIntrinsicId::F64Ge => {
                self.compile_float_compare_intrinsic(compiled_args, FloatPredicate::OGE)
            }
            MirIntrinsicId::F32Eq | MirIntrinsicId::F64Eq => {
                self.compile_float_compare_intrinsic(compiled_args, FloatPredicate::OEQ)
            }
            MirIntrinsicId::F32Ne | MirIntrinsicId::F64Ne => {
                self.compile_float_compare_intrinsic(compiled_args, FloatPredicate::ONE)
            }
            MirIntrinsicId::AtomicU64Exchange
            | MirIntrinsicId::AtomicU64FetchAdd
            | MirIntrinsicId::AtomicU64FetchSub => {
                if compiled_args.len() != 2 {
                    return Err(CodegenError::from(format!(
                        "Atomic U64 operation expected 2 arguments, found {}",
                        compiled_args.len()
                    )));
                }
                let op = match intrinsic {
                    MirIntrinsicId::AtomicU64Exchange => AtomicRMWBinOp::Xchg,
                    MirIntrinsicId::AtomicU64FetchAdd => AtomicRMWBinOp::Add,
                    MirIntrinsicId::AtomicU64FetchSub => AtomicRMWBinOp::Sub,
                    _ => unreachable!(),
                };
                let value = self
                    .builder
                    .build_atomicrmw(
                        op,
                        compiled_args[0].into_pointer_value(),
                        compiled_args[1].into_int_value(),
                        AtomicOrdering::SequentiallyConsistent,
                    )
                    .map_err(|error| {
                        CodegenError::from(format!("Failed atomic U64 operation: {error}"))
                    })?;
                Ok(Some(value.into()))
            }
            MirIntrinsicId::MakeArr => {
                let ptr = compiled_args[0].into_pointer_value();
                let len = compiled_args[1].into_int_value();
                let arr_ty = self.slice_layout_type();
                let mut val = arr_ty.get_undef();
                val = self
                    .builder
                    .build_insert_value(val, ptr, 0, "arr_ptr")
                    .map_err(|e| CodegenError::from(format!("Failed MakeArr ptr: {}", e)))?
                    .into_struct_value();
                val = self
                    .builder
                    .build_insert_value(val, len, 1, "arr_len")
                    .map_err(|e| CodegenError::from(format!("Failed MakeArr len: {}", e)))?
                    .into_struct_value();
                Ok(Some(val.into()))
            }
            MirIntrinsicId::BorrowSlice => {
                let ptr = compiled_args[0].into_pointer_value();
                let len = compiled_args[1].into_int_value();
                let slice_ref_ty = self.slice_layout_type();
                let mut val = slice_ref_ty.get_undef();
                val = self
                    .builder
                    .build_insert_value(val, ptr, 0, "borrow_slice_ptr")
                    .map_err(|e| CodegenError::from(format!("Failed BorrowSlice ptr: {}", e)))?
                    .into_struct_value();
                val = self
                    .builder
                    .build_insert_value(val, len, 1, "borrow_slice_len")
                    .map_err(|e| CodegenError::from(format!("Failed BorrowSlice len: {}", e)))?
                    .into_struct_value();
                Ok(Some(val.into()))
            }
            MirIntrinsicId::BorrowStr => {
                let ptr = compiled_args[0].into_pointer_value();
                let len = compiled_args[1].into_int_value();
                let str_ref_ty = self.slice_layout_type();
                let mut val = str_ref_ty.get_undef();
                val = self
                    .builder
                    .build_insert_value(val, ptr, 0, "borrow_str_ptr")
                    .map_err(|e| CodegenError::from(format!("Failed BorrowStr ptr: {}", e)))?
                    .into_struct_value();
                val = self
                    .builder
                    .build_insert_value(val, len, 1, "borrow_str_len")
                    .map_err(|e| CodegenError::from(format!("Failed BorrowStr len: {}", e)))?
                    .into_struct_value();
                Ok(Some(val.into()))
            }
            other => Err(CodegenError::from(format!("Unknown intrinsic: {other}"))),
        }
    }

    pub(crate) fn compile_intrinsic_values_with_types(
        &mut self,
        intrinsic: MirIntrinsicId,
        compiled_args: &[BasicValueEnum<'ctx>],
        arg_types: &[Type],
        ret_ty: &Type,
    ) -> Result<Option<BasicValueEnum<'ctx>>, CodegenError> {
        if intrinsic.is_value_intrinsic() {
            return self.compile_intrinsic_values(intrinsic, compiled_args, ret_ty);
        }

        match intrinsic {
            MirIntrinsicId::AtomicU64Store => {
                if compiled_args.len() != 2 {
                    return Err(CodegenError::from(format!(
                        "Atomic U64 store expected 2 arguments, found {}",
                        compiled_args.len()
                    )));
                }
                let instruction = self
                    .builder
                    .build_store(
                        compiled_args[0].into_pointer_value(),
                        compiled_args[1].into_int_value(),
                    )
                    .map_err(|error| {
                        CodegenError::from(format!("Failed atomic U64 store: {error}"))
                    })?;
                instruction
                    .set_atomic_ordering(AtomicOrdering::SequentiallyConsistent)
                    .map_err(|error| {
                        CodegenError::from(format!("Failed atomic U64 store ordering: {error}"))
                    })?;
                instruction.set_alignment(8).map_err(|error| {
                    CodegenError::from(format!("Failed atomic U64 store alignment: {error}"))
                })?;
                Ok(None)
            }
            MirIntrinsicId::ArrayRefToSlice => {
                let Type::Reference { inner, .. } = self.resolve_projection_type(ret_ty) else {
                    return Err(CodegenError::from(
                        "ArrayRefToSlice expected slice reference result",
                    ));
                };
                let Type::Slice(_) = inner.as_ref() else {
                    return Err(CodegenError::from(
                        "ArrayRefToSlice expected slice reference result",
                    ));
                };
                let Type::Reference {
                    inner: array_inner, ..
                } = self.resolve_projection_type(&arg_types[0])
                else {
                    return Err(CodegenError::from(
                        "ArrayRefToSlice expected borrowed array input",
                    ));
                };
                let Type::Array(elem, len) = array_inner.as_ref() else {
                    return Err(CodegenError::from(
                        "ArrayRefToSlice expected borrowed array input",
                    ));
                };

                let array_ptr = compiled_args[0].into_pointer_value();
                let zero = self.context.i64_type().const_int(0, false);
                let array_ty = self.llvm_type(&Type::Array(elem.clone(), *len));
                let data_ptr = unsafe {
                    self.builder
                        .build_gep(array_ty, array_ptr, &[zero, zero], "array_ref_slice_ptr")
                        .map_err(|e| {
                            CodegenError::from(format!("Failed ArrayRefToSlice gep: {}", e))
                        })?
                };
                self.make_fat_slice_value(
                    data_ptr,
                    self.context.i64_type().const_int(*len as u64, false),
                )
                .map(Some)
            }
            MirIntrinsicId::ArrayLen => match self.resolve_projection_type(&arg_types[0]) {
                Type::Slice(_) => {
                    let arr = compiled_args[0].into_struct_value();
                    let len = self
                        .builder
                        .build_extract_value(arr, 1, "arr_len")
                        .map_err(|e| {
                            CodegenError::from(format!("Failed to extract array length: {}", e))
                        })?;
                    Ok(Some(len))
                }
                Type::Reference { inner, .. }
                    if matches!(inner.as_ref(), Type::Slice(_) | Type::Str) =>
                {
                    let arr = match compiled_args[0] {
                        BasicValueEnum::PointerValue(ptr) => self
                            .builder
                            .build_load(self.slice_layout_type(), ptr, "slice_ref_load")
                            .map_err(|e| {
                                CodegenError::from(format!("Failed to load slice ref: {}", e))
                            })?
                            .into_struct_value(),
                        value => value.into_struct_value(),
                    };
                    let len = self
                        .builder
                        .build_extract_value(arr, 1, "arr_len")
                        .map_err(|e| {
                            CodegenError::from(format!("Failed to extract array length: {}", e))
                        })?;
                    Ok(Some(len))
                }
                Type::Array(_, len) => Ok(Some(
                    self.context.i64_type().const_int(len as u64, false).into(),
                )),
                Type::Reference { inner, .. } if matches!(inner.as_ref(), Type::Array(_, _)) => {
                    let Type::Array(_, len) = inner.as_ref() else {
                        unreachable!();
                    };
                    Ok(Some(
                        self.context.i64_type().const_int(*len as u64, false).into(),
                    ))
                }
                other => Err(CodegenError::from(format!(
                    "ArrayLen expected slice/array, got {}",
                    other
                ))),
            },
            MirIntrinsicId::PtrOffset => {
                let ptr = compiled_args[0].into_pointer_value();
                let idx = compiled_args[1].into_int_value();
                let ptr_arg_ty = self.normalize_projection_type(&arg_types[0]);
                let elem_ty = match &ptr_arg_ty {
                    Type::Pointer(inner) => self.llvm_type(inner),
                    other => {
                        return Err(CodegenError::from(format!(
                            "PtrOffset expected pointer input, got {other}"
                        )))
                    }
                };
                let result = unsafe {
                    self.builder
                        .build_gep(elem_ty, ptr, &[idx], "ptr_offset")
                        .map_err(|e| CodegenError::from(format!("Failed to build gep: {}", e)))?
                };
                Ok(Some(result.into()))
            }
            MirIntrinsicId::ArrPtr => match self.resolve_projection_type(&arg_types[0]) {
                Type::Slice(_) => {
                    let arr = compiled_args[0].into_struct_value();
                    let ptr = self
                        .builder
                        .build_extract_value(arr, 0, "arr_raw_ptr")
                        .map_err(|e| CodegenError::from(format!("Failed ArrPtr: {}", e)))?;
                    Ok(Some(ptr))
                }
                Type::Reference { inner, .. }
                    if matches!(inner.as_ref(), Type::Slice(_) | Type::Str) =>
                {
                    let arr = match compiled_args[0] {
                        BasicValueEnum::PointerValue(ptr) => self
                            .builder
                            .build_load(self.slice_layout_type(), ptr, "slice_ref_load")
                            .map_err(|e| {
                                CodegenError::from(format!("Failed to load slice ref: {}", e))
                            })?
                            .into_struct_value(),
                        value => value.into_struct_value(),
                    };
                    let ptr = self
                        .builder
                        .build_extract_value(arr, 0, "arr_raw_ptr")
                        .map_err(|e| CodegenError::from(format!("Failed ArrPtr: {}", e)))?;
                    Ok(Some(ptr))
                }
                Type::Array(_, _) => {
                    let temp = self
                        .builder
                        .build_alloca(self.llvm_type(&arg_types[0]), "arr_ptr_tmp")
                        .map_err(|e| CodegenError::from(format!("Failed ArrPtr alloca: {}", e)))?;
                    self.builder
                        .build_store(temp, compiled_args[0])
                        .map_err(|e| CodegenError::from(format!("Failed ArrPtr store: {}", e)))?;
                    let zero = self.context.i64_type().const_int(0, false);
                    let array_ty = self.llvm_type(&arg_types[0]);
                    let ptr = unsafe {
                        self.builder
                            .build_gep(array_ty, temp, &[zero, zero], "arr_raw_ptr")
                            .map_err(|e| CodegenError::from(format!("Failed ArrPtr gep: {}", e)))?
                    };
                    Ok(Some(ptr.into()))
                }
                other => Err(CodegenError::from(format!(
                    "ArrPtr expected slice/array, got {}",
                    other
                ))),
            },
            MirIntrinsicId::SizeOf => {
                let elem_ty = match &arg_types[0] {
                    Type::Pointer(inner) => inner.as_ref(),
                    ty => ty,
                };
                let llvm_ty = self.llvm_type(elem_ty);
                let size_val = llvm_ty
                    .size_of()
                    .unwrap_or_else(|| self.context.i64_type().const_int(8, false));
                let size_i64 = self
                    .builder
                    .build_int_cast(size_val, self.context.i64_type(), "sizeof_i64")
                    .map_err(|e| CodegenError::from(format!("SizeOf cast: {}", e)))?;
                Ok(Some(size_i64.into()))
            }
            MirIntrinsicId::Forget => Ok(None),
            other => Err(CodegenError::from(format!("Unknown intrinsic: {}", other))),
        }
    }

    pub(crate) fn compile_intrinsic_values_with_type_ids(
        &mut self,
        intrinsic: MirIntrinsicId,
        compiled_args: &[BasicValueEnum<'ctx>],
        arg_type_ids: &[TypeId],
        ret_type_id: TypeId,
    ) -> Result<Option<BasicValueEnum<'ctx>>, CodegenError> {
        if self.type_id_contains_projection(ret_type_id)
            || arg_type_ids
                .iter()
                .any(|id| self.type_id_contains_projection(*id))
        {
            let arg_types: Vec<Type> = arg_type_ids
                .iter()
                .map(|id| self.structural_type_for(*id))
                .collect();
            let ret_ty = self.structural_type_for(ret_type_id);
            return self.compile_intrinsic_values_with_types(
                intrinsic,
                compiled_args,
                &arg_types,
                &ret_ty,
            );
        }

        if intrinsic.is_value_intrinsic() {
            let ret_ty = self.structural_type_for(ret_type_id);
            return self.compile_intrinsic_values(intrinsic, compiled_args, &ret_ty);
        }

        match intrinsic {
            MirIntrinsicId::ArrayRefToSlice => {
                let Ty::Reference {
                    inner: ret_inner, ..
                } = self.type_view().ty(ret_type_id)
                else {
                    return Err(CodegenError::from(
                        "ArrayRefToSlice expected slice reference result",
                    ));
                };
                let Ty::Slice(_) = self.type_view().ty(*ret_inner) else {
                    return Err(CodegenError::from(
                        "ArrayRefToSlice expected slice reference result",
                    ));
                };
                let Ty::Reference {
                    inner: array_inner, ..
                } = self.type_view().ty(arg_type_ids[0])
                else {
                    return Err(CodegenError::from(
                        "ArrayRefToSlice expected borrowed array input",
                    ));
                };
                let Ty::Array { len, .. } = self.type_view().ty(*array_inner) else {
                    return Err(CodegenError::from(
                        "ArrayRefToSlice expected borrowed array input",
                    ));
                };

                let array_ptr = compiled_args[0].into_pointer_value();
                let zero = self.context.i64_type().const_int(0, false);
                let array_ty = self.llvm_type_id(*array_inner);
                let data_ptr = unsafe {
                    self.builder
                        .build_gep(array_ty, array_ptr, &[zero, zero], "array_ref_slice_ptr")
                        .map_err(|e| {
                            CodegenError::from(format!("Failed ArrayRefToSlice gep: {}", e))
                        })?
                };
                self.make_fat_slice_value(
                    data_ptr,
                    self.context.i64_type().const_int(*len as u64, false),
                )
                .map(Some)
            }
            MirIntrinsicId::ArrayLen => match self.type_view().ty(arg_type_ids[0]) {
                Ty::Slice(_) => {
                    let arr = compiled_args[0].into_struct_value();
                    let len = self
                        .builder
                        .build_extract_value(arr, 1, "arr_len")
                        .map_err(|e| {
                            CodegenError::from(format!("Failed to extract array length: {}", e))
                        })?;
                    Ok(Some(len))
                }
                Ty::Reference { inner, .. }
                    if matches!(self.type_view().ty(*inner), Ty::Slice(_) | Ty::Str) =>
                {
                    let arr = match compiled_args[0] {
                        BasicValueEnum::PointerValue(ptr) => self
                            .builder
                            .build_load(self.slice_layout_type(), ptr, "slice_ref_load")
                            .map_err(|e| {
                                CodegenError::from(format!("Failed to load slice ref: {}", e))
                            })?
                            .into_struct_value(),
                        value => value.into_struct_value(),
                    };
                    let len = self
                        .builder
                        .build_extract_value(arr, 1, "arr_len")
                        .map_err(|e| {
                            CodegenError::from(format!("Failed to extract array length: {}", e))
                        })?;
                    Ok(Some(len))
                }
                Ty::Reference { inner, .. } => match self.type_view().ty(*inner) {
                    Ty::Array { len, .. } => Ok(Some(
                        self.context.i64_type().const_int(*len as u64, false).into(),
                    )),
                    other => Err(CodegenError::layout(format!(
                        "ArrayLen expected slice/array, got {:?}",
                        other
                    ))),
                },
                Ty::Array { len, .. } => Ok(Some(
                    self.context.i64_type().const_int(*len as u64, false).into(),
                )),
                other => Err(CodegenError::layout(format!(
                    "ArrayLen expected slice/array, got {:?}",
                    other
                ))),
            },
            MirIntrinsicId::PtrOffset => {
                let ptr = compiled_args[0].into_pointer_value();
                let idx = compiled_args[1].into_int_value();
                let ptr_arg_ty =
                    self.normalize_projection_type(&self.structural_type_for(arg_type_ids[0]));
                let elem_ty = match &ptr_arg_ty {
                    Type::Pointer(inner) => self.llvm_type(inner),
                    other => {
                        return Err(CodegenError::from(format!(
                            "PtrOffset expected pointer input, got {other}"
                        )))
                    }
                };
                let result = unsafe {
                    self.builder
                        .build_gep(elem_ty, ptr, &[idx], "ptr_offset")
                        .map_err(|e| CodegenError::from(format!("Failed to build gep: {}", e)))?
                };
                Ok(Some(result.into()))
            }
            MirIntrinsicId::ArrPtr => match self.type_view().ty(arg_type_ids[0]) {
                Ty::Slice(_) => {
                    let arr = compiled_args[0].into_struct_value();
                    let ptr = self
                        .builder
                        .build_extract_value(arr, 0, "arr_raw_ptr")
                        .map_err(|e| CodegenError::from(format!("Failed ArrPtr: {}", e)))?;
                    Ok(Some(ptr))
                }
                Ty::Reference { inner, .. }
                    if matches!(self.type_view().ty(*inner), Ty::Slice(_) | Ty::Str) =>
                {
                    let arr = match compiled_args[0] {
                        BasicValueEnum::PointerValue(ptr) => self
                            .builder
                            .build_load(self.slice_layout_type(), ptr, "slice_ref_load")
                            .map_err(|e| {
                                CodegenError::from(format!("Failed to load slice ref: {}", e))
                            })?
                            .into_struct_value(),
                        value => value.into_struct_value(),
                    };
                    let ptr = self
                        .builder
                        .build_extract_value(arr, 0, "arr_raw_ptr")
                        .map_err(|e| CodegenError::from(format!("Failed ArrPtr: {}", e)))?;
                    Ok(Some(ptr))
                }
                Ty::Array { .. } => {
                    let temp = self
                        .builder
                        .build_alloca(self.llvm_type_id(arg_type_ids[0]), "arr_ptr_tmp")
                        .map_err(|e| CodegenError::from(format!("Failed ArrPtr alloca: {}", e)))?;
                    self.builder
                        .build_store(temp, compiled_args[0])
                        .map_err(|e| CodegenError::from(format!("Failed ArrPtr store: {}", e)))?;
                    let zero = self.context.i64_type().const_int(0, false);
                    let array_ty = self.llvm_type_id(arg_type_ids[0]);
                    let ptr = unsafe {
                        self.builder
                            .build_gep(array_ty, temp, &[zero, zero], "arr_raw_ptr")
                            .map_err(|e| CodegenError::from(format!("Failed ArrPtr gep: {}", e)))?
                    };
                    Ok(Some(ptr.into()))
                }
                other => Err(CodegenError::layout(format!(
                    "ArrPtr expected slice/array, got {:?}",
                    other
                ))),
            },
            MirIntrinsicId::SizeOf => {
                let elem_ty = match self.type_view().ty(arg_type_ids[0]) {
                    Ty::Pointer(inner) => self.llvm_type_id(*inner),
                    _ => self.llvm_type_id(arg_type_ids[0]),
                };
                let size_val = elem_ty
                    .size_of()
                    .unwrap_or_else(|| self.context.i64_type().const_int(8, false));
                let size_i64 = self
                    .builder
                    .build_int_cast(size_val, self.context.i64_type(), "sizeof_i64")
                    .map_err(|e| CodegenError::from(format!("SizeOf cast: {}", e)))?;
                Ok(Some(size_i64.into()))
            }
            MirIntrinsicId::Forget => Ok(None),
            other => {
                let arg_types: Vec<Type> = arg_type_ids
                    .iter()
                    .map(|id| self.structural_type_for(*id))
                    .collect();
                let ret_ty = self.structural_type_for(ret_type_id);
                self.compile_intrinsic_values_with_types(other, compiled_args, &arg_types, &ret_ty)
            }
        }
    }

    fn type_id_contains_projection(&self, id: TypeId) -> bool {
        match self.type_view().ty(id) {
            Ty::Projection { .. } => true,
            Ty::Slice(inner) | Ty::Pointer(inner) | Ty::Reference { inner, .. } => {
                self.type_id_contains_projection(*inner)
            }
            Ty::Array { inner, .. } => self.type_id_contains_projection(*inner),
            Ty::Tuple(elems) => elems
                .iter()
                .any(|elem| self.type_id_contains_projection(*elem)),
            Ty::Function {
                params,
                ret,
                captures,
                ..
            } => {
                params
                    .iter()
                    .any(|param| self.type_id_contains_projection(*param))
                    || self.type_id_contains_projection(*ret)
                    || captures
                        .iter()
                        .any(|capture| self.type_id_contains_projection(capture.ty))
            }
            Ty::Struct { args, .. } | Ty::Enum { args, .. } => args
                .iter()
                .any(|arg| self.type_id_contains_projection(*arg)),
            Ty::Apply { constructor, args } => {
                self.type_id_contains_projection(*constructor)
                    || args
                        .iter()
                        .any(|arg| self.type_id_contains_projection(*arg))
            }
            Ty::Lambda { body, .. } => self.type_id_contains_projection(*body),
            Ty::I8
            | Ty::I16
            | Ty::I32
            | Ty::I64
            | Ty::U8
            | Ty::U16
            | Ty::U32
            | Ty::U64
            | Ty::F32
            | Ty::F64
            | Ty::Bool
            | Ty::Str
            | Ty::Char
            | Ty::Unit
            | Ty::Never
            | Ty::TypeVar(_)
            | Ty::Generic(_)
            | Ty::Constructor { .. }
            | Ty::BoundVar { .. }
            | Ty::Error => false,
        }
    }

    fn compile_int_intrinsic<F>(
        &mut self,
        compiled_args: &[BasicValueEnum<'ctx>],
        label: &str,
        build: F,
    ) -> Result<Option<BasicValueEnum<'ctx>>, CodegenError>
    where
        F: FnOnce(
            &mut Self,
            inkwell::values::IntValue<'ctx>,
            inkwell::values::IntValue<'ctx>,
        )
            -> Result<inkwell::values::IntValue<'ctx>, inkwell::builder::BuilderError>,
    {
        let lhs = compiled_args[0].into_int_value();
        let rhs = compiled_args[1].into_int_value();
        let (lhs, rhs) = self.coerce_int_widths(lhs, rhs)?;
        Ok(Some(
            build(self, lhs, rhs)
                .map_err(|e| CodegenError::from(format!("Failed to build {label}: {e}")))?
                .into(),
        ))
    }

    fn compile_uint_intrinsic<F>(
        &mut self,
        compiled_args: &[BasicValueEnum<'ctx>],
        label: &str,
        build: F,
    ) -> Result<Option<BasicValueEnum<'ctx>>, CodegenError>
    where
        F: FnOnce(
            &mut Self,
            inkwell::values::IntValue<'ctx>,
            inkwell::values::IntValue<'ctx>,
        )
            -> Result<inkwell::values::IntValue<'ctx>, inkwell::builder::BuilderError>,
    {
        let lhs = compiled_args[0].into_int_value();
        let rhs = compiled_args[1].into_int_value();
        let (lhs, rhs) = self.coerce_uint_widths(lhs, rhs)?;
        Ok(Some(
            build(self, lhs, rhs)
                .map_err(|e| CodegenError::from(format!("Failed to build {label}: {e}")))?
                .into(),
        ))
    }

    fn compile_int_compare_intrinsic(
        &mut self,
        compiled_args: &[BasicValueEnum<'ctx>],
        predicate: IntPredicate,
    ) -> Result<Option<BasicValueEnum<'ctx>>, CodegenError> {
        let lhs = compiled_args[0].into_int_value();
        let rhs = compiled_args[1].into_int_value();
        let (lhs, rhs) = self.coerce_int_widths(lhs, rhs)?;
        Ok(Some(
            self.builder
                .build_int_compare(predicate, lhs, rhs, "cmp")
                .map_err(|e| CodegenError::from(format!("Failed to build cmp: {e}")))?
                .into(),
        ))
    }

    fn compile_uint_compare_intrinsic(
        &mut self,
        compiled_args: &[BasicValueEnum<'ctx>],
        predicate: IntPredicate,
    ) -> Result<Option<BasicValueEnum<'ctx>>, CodegenError> {
        let lhs = compiled_args[0].into_int_value();
        let rhs = compiled_args[1].into_int_value();
        let (lhs, rhs) = self.coerce_uint_widths(lhs, rhs)?;
        Ok(Some(
            self.builder
                .build_int_compare(predicate, lhs, rhs, "cmp")
                .map_err(|e| CodegenError::from(format!("Failed to build cmp: {e}")))?
                .into(),
        ))
    }

    fn compile_float_intrinsic<F>(
        &mut self,
        compiled_args: &[BasicValueEnum<'ctx>],
        label: &str,
        build: F,
    ) -> Result<Option<BasicValueEnum<'ctx>>, CodegenError>
    where
        F: FnOnce(
            &mut Self,
            inkwell::values::FloatValue<'ctx>,
            inkwell::values::FloatValue<'ctx>,
        )
            -> Result<inkwell::values::FloatValue<'ctx>, inkwell::builder::BuilderError>,
    {
        let lhs = compiled_args[0].into_float_value();
        let rhs = compiled_args[1].into_float_value();
        Ok(Some(
            build(self, lhs, rhs)
                .map_err(|e| CodegenError::from(format!("Failed to build {label}: {e}")))?
                .into(),
        ))
    }

    fn compile_float_compare_intrinsic(
        &mut self,
        compiled_args: &[BasicValueEnum<'ctx>],
        predicate: FloatPredicate,
    ) -> Result<Option<BasicValueEnum<'ctx>>, CodegenError> {
        let lhs = compiled_args[0].into_float_value();
        let rhs = compiled_args[1].into_float_value();
        Ok(Some(
            self.builder
                .build_float_compare(predicate, lhs, rhs, "cmp")
                .map_err(|e| CodegenError::from(format!("Failed to build cmp: {e}")))?
                .into(),
        ))
    }
}

#[cfg(test)]
mod tests {
    use inkwell::context::Context;
    use inkwell::AddressSpace;

    use crate::codegen::CodeGen;
    use crate::ids::{AssocTypeId, CrateId, DefId, LocalDefId, TypeId};
    use crate::mir::{MirBackendContract, MirIntrinsicId, MirProgram, MirProjectionKey};
    use crate::type_context::TypeContext;
    use crate::types::{AssociatedTypeKey, Type};

    fn load_projection_contract(
        codegen: &mut CodeGen<'_>,
        type_context: TypeContext,
        projection_key: MirProjectionKey,
        output: TypeId,
    ) {
        let mut backend_contract = MirBackendContract::default();
        backend_contract
            .projection_outputs
            .insert(projection_key, output);
        let mir = MirProgram {
            functions: std::collections::BTreeMap::new(),
            type_context,
            backend_contract,
        };

        codegen.compile_program_from_mir(&mir).unwrap();
    }

    #[test]
    fn compile_intrinsic_values_lowers_integer_add() {
        let context = Context::create();
        let mut codegen = CodeGen::new(&context, "test");
        let function_type = context.i64_type().fn_type(
            &[context.i64_type().into(), context.i64_type().into()],
            false,
        );
        let function = codegen.module.add_function("test", function_type, None);
        let entry = context.append_basic_block(function, "entry");
        codegen.builder.position_at_end(entry);

        let lhs = function.get_nth_param(0).unwrap();
        let rhs = function.get_nth_param(1).unwrap();
        let value = codegen
            .compile_intrinsic_values(MirIntrinsicId::I64Add, &[lhs, rhs], &Type::I64)
            .unwrap()
            .unwrap();
        codegen.builder.build_return(Some(&value)).unwrap();

        let ir = codegen.get_ir();
        assert!(ir.contains("add i64"));
        assert!(ir.contains("ret i64"));
    }

    #[test]
    fn compile_intrinsic_values_lowers_atomic_u64_fetch_add() {
        let context = Context::create();
        let mut codegen = CodeGen::new(&context, "test");
        let pointer_type = context.ptr_type(AddressSpace::default());
        let function_type = context
            .i64_type()
            .fn_type(&[pointer_type.into(), context.i64_type().into()], false);
        let function = codegen.module.add_function("test", function_type, None);
        let entry = context.append_basic_block(function, "entry");
        codegen.builder.position_at_end(entry);

        let pointer = function.get_nth_param(0).unwrap();
        let value = function.get_nth_param(1).unwrap();
        let previous = codegen
            .compile_intrinsic_values(
                MirIntrinsicId::AtomicU64FetchAdd,
                &[pointer, value],
                &Type::U64,
            )
            .unwrap()
            .unwrap();
        codegen.builder.build_return(Some(&previous)).unwrap();

        let ir = codegen.get_ir();
        assert!(ir.contains("atomicrmw add ptr"));
        assert!(ir.contains("seq_cst"));
    }

    #[test]
    fn compile_intrinsic_values_lowers_aligned_atomic_u64_store() {
        let context = Context::create();
        let mut codegen = CodeGen::new(&context, "test");
        let pointer_type = context.ptr_type(AddressSpace::default());
        let function_type = context
            .void_type()
            .fn_type(&[pointer_type.into(), context.i64_type().into()], false);
        let function = codegen.module.add_function("test", function_type, None);
        let entry = context.append_basic_block(function, "entry");
        codegen.builder.position_at_end(entry);

        let pointer = function.get_nth_param(0).unwrap();
        let value = function.get_nth_param(1).unwrap();
        codegen
            .compile_intrinsic_values_with_types(
                MirIntrinsicId::AtomicU64Store,
                &[pointer, value],
                &[Type::Pointer(Box::new(Type::U64)), Type::U64],
                &Type::Unit,
            )
            .unwrap();
        codegen.builder.build_return(None).unwrap();

        let ir = codegen.get_ir();
        assert!(ir.contains("store atomic i64"));
        assert!(ir.contains("seq_cst, align 8"));
    }

    #[test]
    fn compile_intrinsic_values_lowers_borrow_slice() {
        let context = Context::create();
        let mut codegen = CodeGen::new(&context, "test");
        let ptr_ty = context.ptr_type(inkwell::AddressSpace::default());
        let function_type = context
            .void_type()
            .fn_type(&[ptr_ty.into(), context.i64_type().into()], false);
        let function = codegen.module.add_function("test", function_type, None);
        let entry = context.append_basic_block(function, "entry");
        codegen.builder.position_at_end(entry);

        let ptr = function.get_nth_param(0).unwrap();
        let len = function.get_nth_param(1).unwrap();
        let _value = codegen
            .compile_intrinsic_values(MirIntrinsicId::BorrowSlice, &[ptr, len], &Type::Unit)
            .unwrap()
            .unwrap();
        codegen.builder.build_return(None).unwrap();

        let ir = codegen.get_ir();
        assert!(ir.contains("borrow_slice_ptr"));
        assert!(ir.contains("borrow_slice_len"));
    }

    #[test]
    fn compile_intrinsic_values_with_type_ids_array_len_handles_slice_ref() {
        let context = Context::create();
        let mut codegen = CodeGen::new(&context, "test");
        let mut type_context = TypeContext::new();
        let slice_id = type_context.intern_type(&Type::Slice(Box::new(Type::I64)));
        let slice_ref_id = type_context.intern_type(&Type::Reference {
            inner: Box::new(Type::Slice(Box::new(Type::I64))),
            mutable: false,
        });
        let i64_id = type_context.intern_type(&Type::I64);
        codegen.set_type_context(type_context);

        let slice_ty = codegen.slice_layout_type();
        let function_type = context.i64_type().fn_type(&[slice_ty.into()], false);
        let function = codegen.module.add_function("test", function_type, None);
        let entry = context.append_basic_block(function, "entry");
        codegen.builder.position_at_end(entry);
        let slice = function.get_nth_param(0).unwrap();

        let value = codegen
            .compile_intrinsic_values_with_type_ids(
                MirIntrinsicId::ArrayLen,
                &[slice],
                &[slice_ref_id],
                i64_id,
            )
            .unwrap()
            .unwrap();
        codegen.builder.build_return(Some(&value)).unwrap();

        let ir = codegen.get_ir();
        assert!(ir.contains("extractvalue"));
        assert!(ir.contains("arr_len"));
        assert!(matches!(
            codegen.type_view().ty(slice_id),
            crate::type_context::Ty::Slice(_)
        ));
    }

    #[test]
    fn compile_intrinsic_values_with_type_ids_array_len_handles_array_ref() {
        let context = Context::create();
        let mut codegen = CodeGen::new(&context, "test");
        let mut type_context = TypeContext::new();
        let array_ref_id = type_context.intern_type(&Type::Reference {
            inner: Box::new(Type::Array(Box::new(Type::I64), 4)),
            mutable: false,
        });
        let i64_id = type_context.intern_type(&Type::I64);
        codegen.set_type_context(type_context);

        let ptr_ty = context.ptr_type(inkwell::AddressSpace::default());
        let function_type = context.i64_type().fn_type(&[ptr_ty.into()], false);
        let function = codegen.module.add_function("test", function_type, None);
        let entry = context.append_basic_block(function, "entry");
        codegen.builder.position_at_end(entry);
        let array_ref = function.get_nth_param(0).unwrap();

        let value = codegen
            .compile_intrinsic_values_with_type_ids(
                MirIntrinsicId::ArrayLen,
                &[array_ref],
                &[array_ref_id],
                i64_id,
            )
            .unwrap()
            .unwrap();
        codegen.builder.build_return(Some(&value)).unwrap();

        let ir = codegen.get_ir();
        assert!(ir.contains("ret i64 4"));
    }

    #[test]
    fn compile_intrinsic_values_with_type_ids_array_len_handles_projected_array_ref() {
        let context = Context::create();
        let mut codegen = CodeGen::new(&context, "test");
        let mut type_context = TypeContext::new();
        let trait_id = DefId::new(CrateId(0), LocalDefId(910));
        let assoc_type_id = AssocTypeId(0);
        let base_ty = Type::Struct {
            id: DefId::new(CrateId(0), LocalDefId(911)),
            args: Vec::new(),
        };
        let trait_arg_ty = Type::Bool;
        let projected_ref_ty = Type::Reference {
            inner: Box::new(Type::Array(Box::new(Type::I64), 6)),
            mutable: false,
        };
        let base_id = type_context.intern_type(&base_ty);
        let trait_arg_id = type_context.intern_type(&trait_arg_ty);
        let projected_ref_id = type_context.intern_type(&projected_ref_ty);
        let projection_id = type_context.intern_type(&Type::Projection {
            ty: Box::new(base_ty),
            trait_id,
            assoc_type: AssociatedTypeKey {
                owner: trait_id,
                assoc_type_id,
            },
            trait_args: vec![trait_arg_ty],
        });
        let i64_id = type_context.intern_type(&Type::I64);
        load_projection_contract(
            &mut codegen,
            type_context,
            MirProjectionKey {
                base: base_id,
                trait_id,
                assoc_type_id,
                trait_args: vec![trait_arg_id],
            },
            projected_ref_id,
        );

        let ptr_ty = context.ptr_type(inkwell::AddressSpace::default());
        let function_type = context.i64_type().fn_type(&[ptr_ty.into()], false);
        let function = codegen.module.add_function("test", function_type, None);
        let entry = context.append_basic_block(function, "entry");
        codegen.builder.position_at_end(entry);
        let projected_ref = function.get_nth_param(0).unwrap();

        let value = codegen
            .compile_intrinsic_values_with_type_ids(
                MirIntrinsicId::ArrayLen,
                &[projected_ref],
                &[projection_id],
                i64_id,
            )
            .unwrap()
            .unwrap();
        codegen.builder.build_return(Some(&value)).unwrap();

        let ir = codegen.get_ir();
        assert!(ir.contains("ret i64 6"));
    }

    #[test]
    fn compile_intrinsic_values_with_type_ids_ptr_offset_uses_projected_pointer_stride() {
        let context = Context::create();
        let mut codegen = CodeGen::new(&context, "test");
        let mut type_context = TypeContext::new();
        let trait_id = DefId::new(CrateId(0), LocalDefId(912));
        let assoc_type_id = AssocTypeId(0);
        let base_ty = Type::Struct {
            id: DefId::new(CrateId(0), LocalDefId(913)),
            args: Vec::new(),
        };
        let projected_ptr_ty = Type::Pointer(Box::new(Type::I64));
        let base_id = type_context.intern_type(&base_ty);
        let projected_ptr_id = type_context.intern_type(&projected_ptr_ty);
        let projection_id = type_context.intern_type(&Type::Projection {
            ty: Box::new(base_ty),
            trait_id,
            assoc_type: AssociatedTypeKey {
                owner: trait_id,
                assoc_type_id,
            },
            trait_args: Vec::new(),
        });
        let i64_id = type_context.intern_type(&Type::I64);
        load_projection_contract(
            &mut codegen,
            type_context,
            MirProjectionKey {
                base: base_id,
                trait_id,
                assoc_type_id,
                trait_args: Vec::new(),
            },
            projected_ptr_id,
        );

        let ptr_ty = context.ptr_type(inkwell::AddressSpace::default());
        let function_type = ptr_ty.fn_type(&[ptr_ty.into(), context.i64_type().into()], false);
        let function = codegen.module.add_function("test", function_type, None);
        let entry = context.append_basic_block(function, "entry");
        codegen.builder.position_at_end(entry);
        let ptr = function.get_nth_param(0).unwrap();
        let index = function.get_nth_param(1).unwrap();

        let value = codegen
            .compile_intrinsic_values_with_type_ids(
                MirIntrinsicId::PtrOffset,
                &[ptr, index],
                &[projection_id, i64_id],
                projection_id,
            )
            .unwrap()
            .unwrap();
        codegen.builder.build_return(Some(&value)).unwrap();

        let ir = codegen.get_ir();
        assert!(ir.contains("getelementptr i64"), "IR was:\n{ir}");
        assert!(!ir.contains("getelementptr i8"), "IR was:\n{ir}");
    }

    #[test]
    fn compile_intrinsic_values_with_type_ids_array_len_rejects_nominal_array_display_name() {
        let context = Context::create();
        let mut codegen = CodeGen::new(&context, "test");
        let mut type_context = TypeContext::new();
        let array_def = DefId::new(CrateId(0), LocalDefId(901));
        let nominal_array_id = type_context.intern_type(&Type::Struct {
            id: array_def,
            args: Vec::new(),
        });
        let i64_id = type_context.intern_type(&Type::I64);
        codegen.set_type_context(type_context);
        codegen
            .struct_names_by_id
            .insert(array_def, "Array".to_string());

        let slice_ty = codegen.slice_layout_type();
        let function_type = context.i64_type().fn_type(&[slice_ty.into()], false);
        let function = codegen.module.add_function("test", function_type, None);
        let entry = context.append_basic_block(function, "entry");
        codegen.builder.position_at_end(entry);
        let nominal_array_value = function.get_nth_param(0).unwrap();

        let error = codegen
            .compile_intrinsic_values_with_type_ids(
                MirIntrinsicId::ArrayLen,
                &[nominal_array_value],
                &[nominal_array_id],
                i64_id,
            )
            .expect_err("nominal struct display name must not drive ArrayLen lowering");

        assert!(error.message.contains("ArrayLen expected slice/array"));
    }

    #[test]
    fn compile_intrinsic_values_with_type_ids_arr_ptr_rejects_nominal_array_display_name() {
        let context = Context::create();
        let mut codegen = CodeGen::new(&context, "test");
        let mut type_context = TypeContext::new();
        let array_def = DefId::new(CrateId(0), LocalDefId(902));
        let nominal_array_id = type_context.intern_type(&Type::Struct {
            id: array_def,
            args: Vec::new(),
        });
        let ret_id = type_context.intern_type(&Type::Pointer(Box::new(Type::U8)));
        codegen.set_type_context(type_context);
        codegen
            .struct_names_by_id
            .insert(array_def, "Array".to_string());

        let slice_ty = codegen.slice_layout_type();
        let ptr_ty = context.ptr_type(inkwell::AddressSpace::default());
        let function_type = ptr_ty.fn_type(&[slice_ty.into()], false);
        let function = codegen.module.add_function("test", function_type, None);
        let entry = context.append_basic_block(function, "entry");
        codegen.builder.position_at_end(entry);
        let nominal_array_value = function.get_nth_param(0).unwrap();

        let error = codegen
            .compile_intrinsic_values_with_type_ids(
                MirIntrinsicId::ArrPtr,
                &[nominal_array_value],
                &[nominal_array_id],
                ret_id,
            )
            .expect_err("nominal struct display name must not drive ArrPtr lowering");

        assert!(error.message.contains("ArrPtr expected slice/array"));
    }

    #[test]
    fn compile_intrinsic_values_with_type_ids_dispatches_type_only_intrinsic_by_typed_id() {
        let context = Context::create();
        let mut codegen = CodeGen::new(&context, "test");
        let mut type_context = TypeContext::new();
        let i64_id = type_context.intern_type(&Type::I64);
        codegen.set_type_context(type_context);

        let function_type = context.i64_type().fn_type(&[], false);
        let function = codegen.module.add_function("test", function_type, None);
        let entry = context.append_basic_block(function, "entry");
        codegen.builder.position_at_end(entry);

        let value = codegen
            .compile_intrinsic_values_with_type_ids(MirIntrinsicId::SizeOf, &[], &[i64_id], i64_id)
            .unwrap()
            .unwrap();
        codegen.builder.build_return(Some(&value)).unwrap();

        let ir = codegen.get_ir();
        assert!(ir.contains("ret i64"));
    }

    #[test]
    fn compile_intrinsic_values_dispatches_by_enum_variant_not_display_name() {
        let context = Context::create();
        let mut codegen = CodeGen::new(&context, "test");
        let function_type = context.i64_type().fn_type(
            &[context.i64_type().into(), context.i64_type().into()],
            false,
        );
        let function = codegen.module.add_function("test", function_type, None);
        let entry = context.append_basic_block(function, "entry");
        codegen.builder.position_at_end(entry);

        let lhs = function.get_nth_param(0).unwrap();
        let rhs = function.get_nth_param(1).unwrap();
        let error = codegen
            .compile_intrinsic_values(MirIntrinsicId::DisplayNameI64Add, &[lhs, rhs], &Type::I64)
            .expect_err("display-only test variant must not dispatch as I64Add");

        assert!(error.message.contains("Unknown intrinsic"));
    }

    #[test]
    fn compile_intrinsic_values_zero_extends_u8_less_than_integer_constant() {
        let context = Context::create();
        let mut codegen = CodeGen::new(&context, "test");
        let function_type = context
            .bool_type()
            .fn_type(&[context.i8_type().into()], false);
        let function = codegen.module.add_function("test", function_type, None);
        let entry = context.append_basic_block(function, "entry");
        codegen.builder.position_at_end(entry);

        let lhs = function.get_nth_param(0).unwrap();
        let rhs = context.i64_type().const_int(255, false).into();
        let value = codegen
            .compile_intrinsic_values(MirIntrinsicId::U8Lt, &[lhs, rhs], &Type::Bool)
            .unwrap()
            .unwrap();
        codegen.builder.build_return(Some(&value)).unwrap();

        let ir = codegen.get_ir();
        assert!(ir.contains("zext"));
        assert!(ir.contains("icmp ult"));
        assert!(!ir.contains("sext"));
        assert!(!ir.contains("icmp slt"));
    }

    #[test]
    fn compile_intrinsic_values_zero_extends_u8_right_shift_integer_constant() {
        let context = Context::create();
        let mut codegen = CodeGen::new(&context, "test");
        let function_type = context
            .i64_type()
            .fn_type(&[context.i8_type().into()], false);
        let function = codegen.module.add_function("test", function_type, None);
        let entry = context.append_basic_block(function, "entry");
        codegen.builder.position_at_end(entry);

        let lhs = function.get_nth_param(0).unwrap();
        let rhs = context.i64_type().const_int(1, false).into();
        let value = codegen
            .compile_intrinsic_values(MirIntrinsicId::U8Shr, &[lhs, rhs], &Type::U64)
            .unwrap()
            .unwrap();
        codegen.builder.build_return(Some(&value)).unwrap();

        let ir = codegen.get_ir();
        assert!(ir.contains("zext"));
        assert!(ir.contains("lshr"));
        assert!(!ir.contains("sext"));
        assert!(!ir.contains("ashr"));
    }
}
